name 'travis_ci_mega'
maintainer 'Travis CI GmbH'
maintainer_email 'contact+packer-templates@travis-ci.org'
license 'MIT'
description 'Installs/Configures travis_ci_mega'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'

# depends 'cassandra'
# depends 'couchdb'
# depends 'elasticsearch'
# depends 'mongodb'
# depends 'neo4j-server'
# depends 'riak'
# depends 'zeromq'
depends 'ant'
depends 'apt'
depends 'bazaar'
depends 'build-essential'
depends 'ccache'
depends 'chromium'
depends 'clang'
depends 'composer'
depends 'dictionaries'
depends 'emacs'
depends 'firefox'
depends 'gimme'
depends 'google-chrome'
depends 'gradle'
depends 'imagemagick'
depends 'jq'
depends 'lein'
depends 'libffi'
depends 'libgdbm'
depends 'libicu'
depends 'libncurses'
depends 'libossp-uuid'
depends 'libqt4'
depends 'maven'
depends 'md5deep'
depends 'memcached'
depends 'mercurial'
depends 'mingw32'
depends 'networking_basic'
depends 'nodejs'
depends 'openssl'
depends 'package-updates'
depends 'postgresql'
depends 'rabbitmq'
depends 'ragel'
depends 'redis'
depends 'rvm'
depends 'scons'
depends 'sphinx'
depends 'sqlite'
depends 'subversion'
depends 'sweeper'
depends 'sysctl'
depends 'system_info'
depends 'travis_build_environment'
depends 'travis_ci_minimal'
depends 'travis_docker'
depends 'travis_git'
depends 'travis_java'
depends 'travis_libevent'
depends 'travis_packer_templates'
depends 'travis_perlbrew'
depends 'travis_phantomjs'
depends 'travis_php'
depends 'travis_python'
depends 'travis_rvm'
depends 'travis_sbt_extras'
depends 'unarchivers'
depends 'vim'
depends 'wget'
depends 'xserver'
