name             'travis_ci_mega'
maintainer       'Travis CI GmbH'
maintainer_email 'contact+packer-templates@travis-ci.org'
license          'MIT'
description      'Installs/Configures travis_ci_mega'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'ant'
depends 'apt'
depends 'bazaar'
depends 'build-essential'
# depends 'cassandra'
depends 'ccache'
depends 'chromium'
depends 'clang'
depends 'composer'
# depends 'couchdb'
depends 'dictionaries'
depends 'docker'
# depends 'elasticsearch'
depends 'emacs'
depends 'firefox'
depends 'gimme'
depends 'git'
depends 'google-chrome'
depends 'imagemagick'
depends 'java'
depends 'jq'
depends 'libevent'
depends 'libffi'
depends 'libgdbm'
depends 'libicu'
depends 'libncurses'
depends 'libossp-uuid'
depends 'libqt4'
depends 'maven'
depends 'md5deep'
depends 'memcached'
depends 'mercurial'
depends 'mingw32'
depends 'mongodb'
# depends 'neo4j-server'
depends 'networking_basic'
depends 'nodejs'
depends 'openssl'
depends 'package-updates'
depends 'phantomjs'
depends 'php'
depends 'postgresql'
depends 'python'
depends 'rabbitmq'
depends 'ragel'
depends 'redis'
# depends 'riak'
depends 'rvm'
depends 'scons'
depends 'sphinx'
depends 'sqlite'
depends 'subversion'
depends 'sweeper'
depends 'sysctl'
depends 'system_info'
depends 'travis_build_environment'
depends 'unarchivers'
depends 'vim'
depends 'wget'
depends 'xserver'
# depends 'zeromq'
