name 'travis_ci_garnet'
maintainer 'Travis CI GmbH'
maintainer_email 'contact+packer-templates@travis-ci.org'
license 'MIT'
description 'Installs/Configures travis_ci_garnet'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'
source_url 'https://github.com/travis-ci/packer-templates'
issues_url 'https://github.com/travis-ci/packer-templates/issues'

depends 'ant'
depends 'chromium'
depends 'emacs'
depends 'firefox'
depends 'google-chrome'
depends 'gradle'
depends 'lein'
depends 'maven'
depends 'memcached'
depends 'mercurial'
depends 'nodejs'
depends 'openssl'
depends 'postgresql'
depends 'redis'
depends 'scons'
depends 'sqlite'
depends 'subversion'
depends 'sweeper'
depends 'travis_build_environment'
depends 'travis_docker'
depends 'travis_java'
depends 'travis_packer_templates'
depends 'travis_phantomjs'
depends 'travis_python'
depends 'travis_sbt_extras'
depends 'travis_system_info'
depends 'unarchivers'
depends 'vim'
depends 'wget'
