---
languages:
- __sugilite__
- android
- c
- c++
- clojure
- cplusplus
- cpp
- crystal
- csharp
- d
- dart
- default
- elixir
- erlang
- go
- groovy
- haskell
- haxe
- java
- julia
- legacy
- mega
- node_js
- perl
- perl6
# FIXME: wat
# - php
- pure_java
- python
- r
- ruby
- rust
- scala
- universe
features:
- basic
- bazaar
- chromium
- docker
- elasticsearch
- emacs
- firefox
- go-toolchain
- google-chrome
- jdk
- memcached
- mongodb
- perlbrew
- phantomjs
- php_interpreter
- postgresql
- rabbitmq
- redis
- sphinxsearch
- sqlite
- xserver
