#!/usr/bin/env bash
set -o errexit
set -o pipefail

unset GEM_PATH

if [[ $# > 1 && $1 = --env ]] ; then
  echo "Running isolated with env ${2}"
  exec env -i HOME=$HOME PATH=$PATH \
    bash -c "source '${2}' && \\
      unset PACKER_LOG && \\
      bash ${BASH_SOURCE[0]}
    "
fi

for f in $(git ls-files '*.yml') ; do
  echo -en "$f "
  ./bin/yml2json < $f | ./bin/json2yml &>/dev/null
  if grep -q ^builders: "$f" ; then
    echo -en "(packer validate ...) "
    packer validate <(bin/yml2json < "$f")
    echo "\`--> ✓"
  else
    echo "✓"
  fi
done

for f in $(git grep -l '^#!/usr/bin/env bash') ; do
  if [[ ! -x "$f" ]] ; then continue ; fi
  echo -en "$f "
  bash -n $f
  echo "✓"
done

if ${RUBOCOP_EXE:-rubocop} --version 2>/dev/null ; then
  ${RUBOCOP_EXE:-rubocop}
else
  bundle exec rubocop
fi

if ${FOODCRITIC_EXE:-foodcritic} --version 2>/dev/null ; then
  ./run-foodcritic cookbooks
else
  FOODCRITIC_EXE='bundle exec foodcritic' ./run-foodcritic cookbooks
fi

./bin/check-language-tags
