#!/usr/bin/env bash
set -o errexit
set -o pipefail

unset GEM_PATH

for f in $(git ls-files '*.yml') ; do
  echo -en "$f "
  ruby -ryaml -e "YAML.load_file('$f')"
  if grep -q ^builders: "$f" ; then
    echo -en "(packer validate ...) "
    packer validate <(bin/yml2json < "$f")
    echo "\`--> ✓"
  else
    echo "✓"
  fi
done

for f in $(git grep -l '^#!/usr/bin/env bash') ; do
  if [[ ! -x "$f" ]] ; then continue ; fi
  echo -en "$f "
  bash -n $f
  echo "✓"
done

rubocop
./run-foodcritic cookbooks
