#!/usr/bin/env bash
# vim:filetype=sh

set -o errexit
set -o pipefail

main() {
  : "${ETC_FAIL2BAN:=/etc/fail2ban}"
  : "${FAIL2BAN_SSH_FILE:=/etc/default/fail2ban-ssh}"

  if [[ -f "${FAIL2BAN_SSH_FILE}" ]]; then
    # shellcheck source=/dev/null
    source "${FAIL2BAN_SSH_FILE}"
  fi

  : "${FAIL2BAN_SSH_MAXRETRY:=4}"
  : "${FAIL2BAN_SSH_BANTIME:=86400}"

  cat >"${ETC_FAIL2BAN}/jail.d/99-enable-sshd.local" <<EOF
# Written via cloud-init :heart:
[sshd]
enabled = true
maxretry = ${FAIL2BAN_SSH_MAXRETRY}
bantime = ${FAIL2BAN_SSH_BANTIME}
EOF

  service fail2ban stop || true
  service fail2ban start || true
}

main "$@"
