#!/usr/bin/env bash
# vim:filetype=sh

set -o errexit

main() {
  if [[ ! "${QUIET}" ]]; then
    set -o xtrace
  fi

  : "${ETCDIR:=/etc}"
  : "${RUNDIR:=/var/tmp/travis-run.d}"

  if [ ! -f "${RUNDIR}/instance-hostname.tmpl" ]; then
    echo "Missing ${RUNDIR}/instance-hostname.tmpl" >&2
    exit 0
  fi

  local hosts_line
  local instance_hostname=localhost
  local instance_id=notset
  local region_zone=notset
  local instance_ipv4=127.0.0.1
  local ec2_metadata='http://169.254.169.254/latest/meta-data'
  local gce_metadata='http://metadata.google.internal/computeMetadata/v1'
  local packet_metadata='https://metadata.packet.net/metadata'

  if curl --connect-timeout 3 -sfSL \
    "${ec2_metadata}/instance-id" &>/dev/null; then
    curl -sSL "${ec2_metadata}/instance-id" >"${RUNDIR}/instance-id"
    instance_id="$(cat "${RUNDIR}/instance-id")"
    instance_id="${instance_id:0:9}"

    curl -sSL "${ec2_metadata}/local-ipv4" \
      >"${RUNDIR}/instance-ipv4"
    instance_ipv4="$(cat "${RUNDIR}/instance-ipv4")"
  fi

  if curl --connect-timeout 3 -sfSL "${packet_metadata}" &>/dev/null; then
    curl -sSL "${packet_metadata}" >"${RUNDIR}/metadata.json"
    instance_id="$(jq -r .id <"${RUNDIR}/metadata.json" | cut -d- -f 1)"

    instance_ipv4="$(
      jq -r ".network.addresses | .[] | \
        select(.address_family==4 and .public==false) | \
        .address" <"${RUNDIR}/metadata.json"
    )"
  fi

  if curl --connect-timeout 3 -sfSL -H 'Metadata-Flavor: Google' \
    "${gce_metadata}/instance" &>/dev/null; then
    curl -sSL -H 'Metadata-Flavor: Google' \
      "${gce_metadata}/instance/id" >"${RUNDIR}/instance-id"
    instance_id="$(cat "${RUNDIR}/instance-id")"
    instance_id="${instance_id:0:9}"

    curl -sSL -H 'Metadata-Flavor: Google' \
      "${gce_metadata}/instance/network-interfaces/0/ip" \
      >"${RUNDIR}/instance-ipv4"
    instance_ipv4="$(cat "${RUNDIR}/instance-ipv4")"

    curl -sSL -H 'Metadata-Flavor: Google' \
      "${gce_metadata}/instance/zone" |
      awk -F/ '{ print $NF }' >"${RUNDIR}/instance-region-zone"
    region_zone="$(cat "${RUNDIR}/instance-region-zone")"
  fi

  instance_hostname="$(
    sed -e "s/___INSTANCE_ID___/${instance_id}/g" \
      -e "s/___REGION_ZONE___/${region_zone}/g" \
      <"${RUNDIR}/instance-hostname.tmpl"
  )"
  hosts_line="${instance_ipv4} ${instance_hostname} ${instance_hostname%%.*}"

  echo "${instance_hostname}" |
    tee "${ETCDIR}/hostname" >"${RUNDIR}/instance-hostname"
  hostname -F "${ETCDIR}/hostname"

  if ! grep -q "^${hosts_line}" "${ETCDIR}/hosts"; then
    echo "${hosts_line}" | tee -a "${ETCDIR}/hosts"
  fi
}

main "$@"
