#!/usr/bin/env bash
# vim:filetype=sh

set -o errexit
set -o pipefail

main() {
  : "${RSYSLOG_PAPERTRAIL_CONF:=/etc/rsyslog.d/65-papertrail.conf}"
  : "${SYSLOG_ADDRESS_FILE:=/var/tmp/travis-run.d/syslog-address}"

  if [[ ! -f "${SYSLOG_ADDRESS_FILE}" ]]; then
    echo "Missing ${SYSLOG_ADDRESS_FILE}"
    exit 0
  fi

  local syslog_address
  syslog_address="$(cat "${SYSLOG_ADDRESS_FILE}")"

  touch "${RSYSLOG_PAPERTRAIL_CONF}"
  sed -i '/^\*\.\*.*@/d' "${RSYSLOG_PAPERTRAIL_CONF}"
  echo "*.* @${syslog_address}" >>"${RSYSLOG_PAPERTRAIL_CONF}"

  service rsyslog stop || true
  service rsyslog start || true
}

main "$@"
