name 'travis_ci_amethyst'
maintainer 'Travis CI GmbH'
maintainer_email 'contact+packer-templates@travis-ci.org'
license 'MIT'
description 'Installs/Configures travis_ci_amethyst'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.1.0'
source_url 'https://github.com/travis-ci/packer-templates'
issues_url 'https://github.com/travis-ci/packer-templates/issues'

# depends 'cassandra'
# depends 'couchdb'
# depends 'elasticsearch'
# depends 'neo4j-server'
# depends 'riak'
# depends 'zeromq'
depends 'ant'
depends 'apt'
depends 'bazaar'
depends 'ccache'
depends 'chromium'
depends 'clang'
depends 'dictionaries'
depends 'emacs'
depends 'firefox'
depends 'google-chrome'
depends 'gradle'
depends 'jq'
depends 'maven'
depends 'md5deep'
depends 'memcached'
depends 'mercurial'
depends 'nodejs'
depends 'openssl'
depends 'postgresql'
depends 'redis'
depends 'scons'
depends 'sqlite'
depends 'subversion'
depends 'sweeper'
depends 'sysctl'
depends 'travis_build_environment'
depends 'travis_cmake'
depends 'travis_docker'
depends 'travis_git'
depends 'travis_java'
depends 'travis_packer_templates'
depends 'travis_perlbrew'
depends 'travis_phantomjs'
depends 'travis_php'
depends 'travis_python'
depends 'travis_sphinxsearch'
depends 'travis_system_info'
depends 'unarchivers'
depends 'vim'
depends 'wget'
depends 'xserver'
