#!/usr/bin/env bash

set -o errexit

main() {

  local version="1.10.14"

  echo "Download and extract Ant"
  wget -q "https://downloads.apache.org/ant/binaries/apache-ant-${version}-bin.tar.gz"
  tar xzf apache-ant-$version-bin.tar.gz
  sudo mv apache-ant-$version/ /usr/local/ant
  echo "Add Ant variables to a profile"
  echo 'ANT_HOME="/usr/local/ant"
  PATH="$PATH:/usr/local/ant/bin"
  export ANT_HOME
  export PATH'  > /etc/profile
  cat /etc/profile

}

main "$@"
