#!/usr/bin/env bash

set -o errexit

main() {

  local version="1.10.15"

  echo "Download and extract Ant"
  wget -q "https://downloads.apache.org/ant/binaries/apache-ant-${version}-bin.tar.gz"
  tar xzf apache-ant-$version-bin.tar.gz
  sudo mv apache-ant-$version/ /usr/local/ant
  
  echo "Add Ant variables to a profile"

  echo "export ANT_HOME=/usr/local/ant" >> /etc/profile
  echo "export PATH=\$PATH:/usr/local/ant/bin" >> /etc/profile
  

  export ANT_HOME=/usr/local/ant
  export PATH="$PATH:/usr/local/ant/bin"
  

  cat /etc/profile

}

main "$@"
