#!/usr/bin/env bash

set -o errexit
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

mv /var/tmp/apt-conf-90translations /etc/apt/apt.conf.d/90translations
mv /var/tmp/generate-ssh-host-keys /usr/local/sbin/generate-ssh-host-keys
mv /var/tmp/ssh-keygen.init /etc/init.d/ssh-keygen

chown root:root /etc/init.d/ssh-keygen /usr/local/sbin/generate-ssh-host-keys
chmod 0750 /etc/init.d/ssh-keygen /usr/local/sbin/generate-ssh-host-keys

update-rc.d ssh-keygen defaults

apt-get update -yqq
apt-get upgrade -yqq
