#!/usr/bin/env bash

set -o errexit
set -o xtrace

rm -rf \
  VBoxGuestAdditions_*.iso \
  VBoxGuestAdditions_*.iso.? \
  /opt/chef \
  /tmp/packer* \
  /var/log/installer \
  /var/lib/man-db \
  /var/lib/apt/lists/* \
  /var/tmp/* \
  /etc/ssh/ssh_host_* \
  /etc/apparmor* \
  /etc/systemd \
  /lib/recovery-mode

if [[ -d /home/travis ]] ; then
  rm -f /home/travis/linux.iso /home/travis/shutdown.sh
fi

for f in $(find /var/log -type f) ; do
  dd if=/dev/null of=$f
done
