#!/usr/bin/env bash

set -o errexit
set -o xtrace

mkdir -p /tmp/chef-stuff
cd /tmp/chef-stuff

if [[ -d travis-cookbooks ]] ; then
  rm -rf ./travis-cookbooks
fi

git clone \
  --depth=10 \
  --branch=${TRAVIS_COOKBOOKS_BRANCH:-master} \
  ${COOKBOOKS_URL:-https://github.com/travis-ci/travis-cookbooks.git}

if [[ ${TRAVIS_COOKBOOKS_SHA} ]] ; then
  pushd travis-cookbooks
  git checkout -qf "${TRAVIS_COOKBOOKS_SHA}"
  popd
fi

pushd travis-cookbooks
pwd > /var/tmp/packer-env/TRAVIS_COOKBOOKS_DIR
git log -1 --format=%h > /var/tmp/packer-env/TRAVIS_COOKBOOKS_SHA
popd
