#!/usr/bin/env bash
set -ex
mkdir -p /tmp/chef-stuff
cd /tmp/chef-stuff
[[ -d travis-cookbooks ]] && rm -rf ./travis-cookbooks
git clone \
  --depth=10 \
  --branch=${COOKBOOKS_BRANCH:-master} \
  ${COOKBOOKS_URL:-https://github.com/travis-ci/travis-cookbooks.git}
