#!/usr/bin/env bash
set -ex
mkdir -p /tmp/chef-stuff
cd /tmp/chef-stuff

if [[ -d travis-cookbooks ]] ; then
  rm -rf ./travis-cookbooks
fi

git clone \
  --depth=10 \
  --branch=${COOKBOOKS_BRANCH:-master} \
  ${COOKBOOKS_URL:-https://github.com/travis-ci/travis-cookbooks.git}

if [[ ${COOKBOOKS_SHA} ]] ; then
  pushd travis-cookbooks
  git checkout -qf "${COOKBOOKS_SHA}"
  popd
fi

# XXX: hackety hack
if [[ ${INTERNAL} ]] ; then
  pushd travis-cookbooks/worker_host
  rm -rf users
  git clone \
    --depth=10 \
    --branch=master \
    https://github.com/travis-infrastructure/users-cookbook.git users
fi
