#!/usr/bin/env bash

set -o errexit

main() {
  set -o xtrace

  export DEBIAN_FRONTEND=noninteractive

  echo 1 >/proc/sys/net/ipv4/ip_forward
  echo net.ipv4.ip_forward=1 >>/etc/sysctl.conf
  iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
  iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT
  apt-get update -yqq
  apt-get install -yqq iptables-persistent
}

main "${@}"
