#!/usr/bin/env bash
set -o errexit

main() {
  : "${JOB_BOARD_REGISTER_FILE:=/c/travis-job-board-register.yml}"

  local nowtime
  nowtime=$(date -u +%Y%m%dT%H%M%SZ)

  cat >"${JOB_BOARD_REGISTER_FILE}" <<EOF
---
stack: onion
languages:
- powershell
features:
- dotnet
tags:
  dist: $JOB_BOARD_IMAGE_DIST
  os: windows
  packer_chef_time: "${nowtime}"
  language_powershell: true
  language_sh: true
  language_bash: true
  language_shell: true
  language_script: true
  language_node_js: true
  language_go: true
  language_rust: true
  feature_dotnet: true
tags_string: "dist:$JOB_BOARD_IMAGE_DIST,os:windows,packer_chef_time:${nowtime},language_powershell:true,language_sh:true,language_bash:true,language_shell:true,language_script:true,language_node_js:true,language_go:true,language_rust:true,feature_dotnet:true"
EOF
}

main "$@"
