#!/usr/bin/env bash

set -o errexit
set -o xtrace

main() {
  : "${IMAGE_METADATA_TARBALL:=/var/tmp/image-metadata.tar.bz2}"
  : "${PACKER_ENV_DIR:=/.packer-env}"
  : "${JOB_BOARD_REGISTER_FILE:=/.job-board-register.yml}"
  : "${NODE_ATTRIBUTES_YML:=/.node-attributes.yml}"
  : "${RSPEC_JSON_DIR:=/home/travis}"
  : "${SYSTEM_INFO_JSON:=/usr/share/travis/system_info.json}"

  pushd "${TMPDIR:-/var/tmp}"
  local dest
  dest="${IMAGE_METADATA_TARBALL##*/}"
  dest="${dest%%.tar.bz2}"
  mkdir -p "${dest}/env"

  find "${RSPEC_JSON_DIR}" \
    -maxdepth 1 \
    -name '.*_rspec.json' \
    | while read -r rspec_json; do
      cp -v "${rspec_json}" "${dest}/${rspec_json##*/.}"
    done

  rsync -av "${PACKER_ENV_DIR}/" "${dest}/env/"
  cp -v "${JOB_BOARD_REGISTER_FILE}" "${dest}/job-board-register.yml"
  cp -v "${NODE_ATTRIBUTES_YML}" "${dest}/node-attributes.yml"
  cp -v "${SYSTEM_INFO_JSON}" "${dest}/system_info.json"
  tar -cjvf "${IMAGE_METADATA_TARBALL}" "${dest}"
}

main "$@"
