#!/usr/bin/env bash

set -o errexit
set -o xtrace

main() {
  : ${IMAGE_METADATA_TARBALL:=/var/tmp/image-metadata.tar.bz2}
  : ${PACKER_ENV_DIR:=/.packer-env}
  : ${JOB_BOARD_REGISTER_FILE:=/etc/default/job-board-register}

  pushd "${TMPDIR:-/var/tmp}"
  local dest="$(basename "${IMAGE_METADATA_TARBALL}" .tar.bz2)"
  mkdir -p "${dest}/env"

  rsync -av "${PACKER_ENV_DIR}/" "${dest}/env/"
  cp -v "${JOB_BOARD_REGISTER_FILE}" "${dest}/job-board-register"
  tar -cjvf "${IMAGE_METADATA_TARBALL}" "${dest}"
}

main "$@"
