#!/usr/bin/env bash
set -o errexit

main() {
  : "${BIN_LIB_CHECKSUMS:=/.bin-lib.SHA256SUMS}"

  # shellcheck disable=SC2086
  __checksum \
    /lib \
    /usr/lib \
    /usr/local/lib \
    ${PATH//:/ } \
    >"${BIN_LIB_CHECKSUMS}"
}

__checksum() {
  find "${@}" \
    -executable -type f -print0 \
    -or -name '*.so' -print0 \
    -or -name '*.a' -print0 2>/dev/null |
    xargs -0 sha256sum 2>/dev/null |
    sort -k2
}

main "$@"
