#!/usr/bin/env bash

set -o errexit

main() {
  # Start travis-worker, but only long enough to pull images
  start travis-worker
  rm /var/tmp/travis-worker.conf
  rm /var/tmp/travis-worker.service
  pkill -INT travis-worker
}
