#!/usr/bin/env bash

set -ex
set -o errexit

main() {
  # Start travis-worker, but only long enough to pull images
  #echo "Starting travis-worker"
  #start travis-worker
  #echo "Removing travis-worker.conf"
  #rm /var/tmp/travis-worker.conf
  #echo "Removing travis-worker.service"
  #rm /var/tmp/travis-worker.service
  #echo "Killing travis-worker"
  #pkill -INT travis-worker
  docker info
  service docker stop
  echo 'DOCKER_OPTS="-g /mnt/docker --storage-driver overlay2"' | sudo tee -a /etc/default/docker
  service docker start
  docker info
  mkfs -t ext3 /dev/xvdx
  mount /dev/xvdx /mnt -o _netdev
  docker pull alpine
  umount /mnt
}

main "$@"
