#!/usr/bin/env bash

set -o errexit

main() {
  : ${TRAVIS_USER_PASSWORD:=travis}

  if [[ ${TRAVIS_OBFUSCATE_PASSWORD} ]] ; then
    TRAVIS_USER_PASSWORD="$(dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64)"
  fi

  getent passwd | grep -q travis
  echo "travis:${TRAVIS_USER_PASSWORD}" | chpasswd

  [[ -d /home/travis ]]

  for f in .ssh/authorized_keys .ssh/known_hosts ; do
    mkdir -p /home/travis/$(dirname $f)
    touch /home/travis/$f
    chmod 0600 /home/travis/$f
  done

  echo '# this space intentionally left blank' > /home/travis/.ssh/authorized_keys

  mkdir -p /opt
  chmod 0755 /opt
  chown -R travis:travis /home/travis /opt
}

main "$@"
