#!/usr/bin/env bash
set -ex

[[ $TARFILE ]]
[[ $IMAGE  ]]

if ! docker version ; then
  curl https://get.docker.io | bash
fi

CONTAINER_ID="$(docker run -dit "$IMAGE" echo)"
docker export "$CONTAINER_ID" > $TARFILE

dpkg -l | awk '{ print $2 }' | grep docker | xargs apt-get purge -y
rm -rf /var/lib/docker

tar -tvf $TARFILE > /.ci-docker-import-tarfile-manifest.log

(
  set +e
  tar -C / --exclude-from=/var/tmp/excludes -xf $TARFILE 2>&1 | \
    tee /.ci-docker-import.log
) || echo "tar exit $? suppressed"
