#!/usr/bin/env bash

# Download CouchDB .deb file an install it

set -o errexit

sudo apt update && sudo apt install -y curl apt-transport-https gnupg
curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1
source /etc/os-release
echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null

sudo apt install -y couchdb

echo -e '[native_query_servers]\nerlang = {couch_native_process, start_link, []}' | sudo tee /opt/couchdb/etc/local.d/erlang_query_server.ini
echo -e '[admins]\nadmin = travis' | sudo tee /opt/couchdb/etc/local.d/admins.ini

sudo chown -R couchdb:couchdb /opt/couchdb/
sudo systemctl disable couchdb

sudo systemctl restart couchdb
sleep 10
curl http://admin:travis@127.0.0.1:5984