#!/usr/bin/env bash

set -o errexit
set -o xtrace

export DEBIAN_FRONTEND='noninteractive'

if [[ ${PACKER_BUILDER_TYPE} =~ vmware ]]; then
  APT_GET_INSTALL_PRE_CHEF='open-vm-tools'
fi

rm -vf /etc/apt/sources.list.d/partner.list

apt-get update -yqq
apt-get install -yqq \
  --no-install-suggests \
  --no-install-recommends \
  at \
  cron \
  curl \
  git \
  sudo \
  wget \
  ${APT_GET_INSTALL_PRE_CHEF}

mkdir -p /tmp/chef-stuff/cookbooks

git clone --branch=v1.3.4 git://github.com/opscode-cookbooks/openssh.git /tmp/chef-stuff/cookbooks/openssh
git clone --branch=v2.7.0 git://github.com/opscode-cookbooks/apt.git /tmp/chef-stuff/cookbooks/apt
git clone --branch=v1.1.6 git://github.com/opscode-cookbooks/chef_handler.git /tmp/chef-stuff/cookbooks/chef_handler
git clone --branch=v2.7.1 git://github.com/opscode-cookbooks/sudo.git /tmp/chef-stuff/cookbooks/sudo
git clone git://github.com/travis-infrastructure/users-cookbook.git /tmp/chef-stuff/cookbooks/users
git clone git://github.com/travis-ci/travis-cookbooks.git /tmp/chef-stuff/travis-cookbooks

git --git-dir=/tmp/chef-stuff/cookbooks/users/.git --work-tree=/tmp/chef-stuff/cookbooks/users checkout 9b807fc8a131383d3b43b9a92a17be7f35520d52
git --git-dir=/tmp/chef-stuff/travis-cookbooks/.git --work-tree=/tmp/chef-stuff/travis-cookbooks checkout 5d4d4dea02071bcbf52a73c80bab40e6b480b134
