#!/usr/bin/env bash

set -o errexit
set -o xtrace

export DEBIAN_FRONTEND='noninteractive'

cp /var/tmp/travis-user-shutdown-implode /usr/local/bin/travis-user-shutdown-implode
chown root:root /usr/local/bin/travis-user-shutdown-implode
chmod 0700 /usr/local/bin/travis-user-shutdown-implode

rm -vf /etc/apt/sources.list.d/partner.list

apt-get update -yqq
apt-get upgrade -yqq
