#!/usr/bin/env bash

set -o errexit

main() {
  shopt -s nullglob

  if [[ -f /etc/default/job-board-register ]] ; then
    source /etc/default/job-board-register
  fi

  : ${PACKER_ENV_DIR:=/.packer-env}
  : ${SKIP_ON_BUILDER_TYPE:-docker}

  [[ $JOB_BOARD_IMAGES_URL ]] || {
    __log Missing \$JOB_BOARD_IMAGES_URL
    exit 1
  }

  [[ $IMAGE_NAME ]] || {
    __log Missing \$IMAGE_NAME
    exit 1
  }

  if [[ -d ${PACKER_ENV_DIR} ]] ; then
    for f in ${PACKER_ENV_DIR}/* ; do
      eval "export $(basename $f)='$(cat $f)'"
    done
  fi

  if [[ "x${PACKER_BUILDER_TYPE}" != 'x' && \
        "x${SKIP_ON_BUILDER_TYPE}" != 'x' && \
        "x${PACKER_BUILDER_TYPE}" == "x${SKIP_ON_BUILDER_TYPE}" ]] ; then
    __log Skipping registration on $PACKER_BUILDER_TYPE
    set +o errexit
    exit 0
  fi

  env | grep -E '^(PACKER|TRAVIS|TAGS|IMAGE_NAME)' | sort

  : ${TAGS:=nonempty:true}
  : ${GROUP:=$(__group)}
  : ${DIST:=$(__dist)}
  : ${OS:=$(__uname)}

  TAGS="${TAGS},os:${OS},group:${GROUP},dist:${DIST}"
  TAGS="${TAGS},packer_templates_branch:${PACKER_TEMPLATES_BRANCH}"
  TAGS="${TAGS},packer_templates_sha:${PACKER_TEMPLATES_SHA}"
  TAGS="${TAGS},travis_cookbooks_branch:${TRAVIS_COOKBOOKS_BRANCH}"
  TAGS="${TAGS},travis_cookbooks_sha:${TRAVIS_COOKBOOKS_SHA}"

  if [[ $PACKER_BUILD_NAME ]] ; then
    TAGS="$TAGS,packer_build_name:$PACKER_BUILD_NAME"
  fi

  if [[ $PACKER_BUILDER_TYPE ]] ; then
    TAGS="$TAGS,packer_builder_type:$PACKER_BUILDER_TYPE"

    case "$PACKER_BUILDER_TYPE" in
      googlecompute) IMAGE_INFRA=gce ;;
      docker) IMAGE_INFRA=docker ;;
      vmware) IMAGE_INFRA=jupiterbrain ;;
    esac
  fi

  : ${IMAGE_INFRA:=local}

  local curl_params="infra=$(__uri_esc "${IMAGE_INFRA}")"
  curl_params="${curl_params}&name=$(__uri_esc "${IMAGE_NAME}")"
  curl_params="${curl_params}&tags=$(__uri_esc "${TAGS}")"

  __log "msg=\"registering with job board\"" \
    "name=${IMAGE_NAME} infra=${IMAGE_INFRA} tags=${TAGS}"
  __log "curl_params=\"${curl_params}\""

  curl -s -X POST "$JOB_BOARD_IMAGES_URL?${curl_params}" | jq .
}

__group() {
  if [[ $TRAVIS_COOKBOOKS_BRANCH = ${TRAVIS_COOKBOOKS_EDGE_BRANCH:-master} && \
    ! ${TRAVIS_COOKBOOKS_SHA:-dirty} =~ dirty && \
    $PACKER_TEMPLATES_BRANCH = master && \
    ! ${PACKER_TEMPLATES_SHA:-dirty} =~ dirty ]] ; then
    echo edge
    return
  fi
  echo dev
}

__dist() {
  lsb_release -sc 2>/dev/null || sw_vers -productVersion 2>/dev/null
}

__uname() {
  local uname_lower=$(uname | tr '[:upper:]' '[:lower:]')
  if [[ $uname_lower = darwin ]] ; then
    echo osx
    return
  fi
  echo $uname_lower
}

__uri_esc() {
  echo "\"${1}\"" | jq -r '. | @uri'
}

__log() {
  echo "time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$@"
}

main "$@"
