#!/usr/bin/env bash

set -o errexit
set -o xtrace

if [[ $PACKER_BUILDER_TYPE = googlecompute || \
      $PACKER_BUILDER_TYPE = amazon-ebs ]] ; then
  echo "Skipping minimization on $PACKER_BUILDER_TYPE"
  exit 0
fi

if [[ $PACKER_BUILDER_TYPE != docker ]] ; then
  readonly SWAP_UUID=$(/sbin/blkid -o value -l -s UUID -t TYPE=swap)

  if [[ $SWAP_UUID ]] ; then
    readonly SWAP_PART=$(readlink -f /dev/disk/by-uuid/"$SWAP_UUID")
    /sbin/swapoff "$SWAP_PART"
    dd if=/dev/zero of="$SWAP_PART" bs=1M || echo "dd exit $? suppressed"
    /sbin/mkswap -U "$SWAP_UUID" "$SWAP_PART"
  fi
fi

dd if=/dev/zero of=/EMPTY bs=1M || echo "dd exit $? suppressed"
rm -f /EMPTY
sync

vmware-toolbox-cmd disk shrink / || echo "vmware-toolbox-cmd exit $? suppressed"
vmware-toolbox-cmd disk shrink /boot || echo "vmware-toolbox-cmd exit $? suppressed"
