#!/usr/bin/env bash
set -ex

readonly swapuuid=$(/sbin/blkid -o value -l -s UUID -t TYPE=swap)
readonly swappart=$(readlink -f /dev/disk/by-uuid/"$swapuuid")
/sbin/swapoff "$swappart"
dd if=/dev/zero of="$swappart" bs=1M || echo "dd exit $? suppressed"
/sbin/mkswap -U "$swapuuid" "$swappart"
dd if=/dev/zero of=/EMPTY bs=1M || echo "dd exit $? suppressed"
rm -f /EMPTY
sync
vmware-toolbox-cmd disk shrink / || echo "vmware-toolbox-cmd exit $? suppressed"
vmware-toolbox-cmd disk shrink /boot || echo "vmware-toolbox-cmd exit $? suppressed"
