#!/usr/bin/env bash

set -o errexit
set -o xtrace

main() {
  : ${PACKER_ENV_TAR:=/.packer-env.tar.bz2}
  : ${PACKER_ENV_DIR:=/.packer-env}
  pushd "${TMPDIR:-/var/tmp}"
  local dest="$(basename "${PACKER_ENV_TAR}" .tar.bz2)"
  mkdir -p "${dest}"
  rsync -av "${PACKER_ENV_DIR}/" "${dest}/"
  tar -cjvf "${PACKER_ENV_TAR}" "${dest}"
}

main "$@"
