#!/usr/bin/env bash

set -o errexit
set -o xtrace

mkdir -p /.packer-env

for var in $(env | grep -E '^(PACKER|TRAVIS)' | awk -F= '{ print $1 }') ; do
  eval "echo \$$var" > /.packer-env/$var
done

if [[ -f /var/tmp/git-meta/packer-templates-branch ]] ; then
  cp -v \
    /var/tmp/git-meta/packer-templates-branch \
    /.packer-env/PACKER_TEMPLATES_BRANCH
fi

if [[ -f /var/tmp/git-meta/packer-templates-sha ]] ; then
  cp -v \
    /var/tmp/git-meta/packer-templates-sha \
    /.packer-env/PACKER_TEMPLATES_SHA
fi
