#!/usr/bin/env bash

set -o errexit

main() {
  set -o xtrace
  shopt -s nullglob

  export DEBIAN_FRONTEND='noninteractive'

  if [[ "${PACKER_BUILDER_TYPE}" != docker ]]; then
    __disable_ipv6
  fi
  __install_packages
  __upgrade_apt
  __setup_sshd
  __setup_travis_user
}

__disable_ipv6() {
  sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
}

__install_packages() {
  if [[ "${PACKER_BUILDER_TYPE}" =~ vmware ]]; then
    APT_GET_INSTALL_PRE_CHEF='open-vm-tools'
  fi

  if [[ "${PACKER_BUILDER_TYPE}" =~ googlecompute ]]; then
    rm -rvf /etc/apt/sources.list.d/partner.list \
      /var/lib/apt/lists/*
  fi

  apt-get update -yqq
  apt-get install -yqq \
    --no-install-suggests \
    --no-install-recommends \
    ca-certificates \
    cron \
    curl \
    git \
    sudo \
    wget \
    python \
    ${APT_GET_INSTALL_PRE_CHEF}
}

__upgrade_apt() {
  curl -sSL https://packagecloud.io/install/repositories/computology/apt-backport/script.deb.sh \
    | bash
  apt-get update -yqq
  apt-get install -yqq apt=1.2.10
  apt-get clean -yqq
  rm -rf /var/lib/apt/lists
  apt-get update -yqq
}

__setup_sshd() {
  mkdir -p /var/run/sshd

  if ! grep -Eq '^sshd: ALL: ALLOW' /etc/hosts.allow; then
    echo 'sshd: ALL: ALLOW' >>/etc/hosts.allow
  fi
}

__setup_travis_user() {
  if ! getent passwd travis &>/dev/null; then
    if [[ "$TRAVIS_UID_1000" == noforce ]]; then
      useradd -p travis -s /bin/bash -m travis
    else
      useradd -p travis -s /bin/bash -m travis -u 1000
      groupmod -g 1000 travis
      usermod -u 1000 travis
    fi
  fi

  echo travis:travis | chpasswd

  __setup_sudoers
  __setup_travis_ssh

  mkdir -p /opt
  chmod 0755 /opt
  chown -R travis:travis /home/travis /opt
}

__setup_sudoers() {
  sed -i '/^%/d;/^# /d;/^$/d;/^#$/d;/^#includedir/d' /etc/sudoers
  echo '#includedir /etc/sudoers.d' >>/etc/sudoers

  mkdir -p /etc/sudoers.d

  if [[ -f /var/tmp/sudoers.d-travis ]]; then
    cp -v /var/tmp/sudoers.d-travis /etc/sudoers.d/travis
  else
    cat >/etc/sudoers.d/travis <<EOF
travis ALL=(ALL) NOPASSWD:ALL
Defaults !authenticate
Defaults !env_reset
Defaults !mail_badpass
EOF
  fi
  chmod 440 /etc/sudoers.d/travis
}

__setup_travis_ssh() {
  mkdir -p /home/travis/.ssh
  chmod 0700 /home/travis/.ssh

  touch /home/travis/.ssh/authorized_keys
  for f in /var/tmp/*_rsa.pub; do
    cat "${f}" >>/home/travis/.ssh/authorized_keys
  done
  chmod 0600 /home/travis/.ssh/authorized_keys
}

main "$@"
