#!/usr/bin/env bash

set -o errexit
set -o xtrace

main() {

# Install pyenv-update plugin
git config --global --add safe.directory /opt/pyenv
cd /opt/pyenv/bin/
git checkout master
git clone https://github.com/pyenv/pyenv-update.git "$(/opt/pyenv/bin/pyenv root)"/plugins/pyenv-update
/opt/pyenv/bin/pyenv update
/opt/pyenv/bin/pyenv rehash && hash -r

}

main "$@"
