#!/bin/bash

 sudo apt remove --purge rabbitmq-server erlang*
 curl -1sLf 'https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/setup.deb.sh' | sudo -E bash
 sudo apt update -y
 sudo apt install --upgrade erlang -y
 wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.3/rabbitmq-server_3.13.3-1_all.deb
 sudo dpkg -i rabbitmq-server_3.13.3-1_all.deb
 rm rabbitmq-server_3.13.3-1_all.deb
