#!/usr/bin/env bash

set -o errexit

main() {
  set -o xtrace

  for u in ${DEFAULT_USERS:-vagrant ubuntu} ; do
    if [[ $(whoami) = ${u} ]] ; then
      echo 'Refusing to remove myself' >&2
      continue
    fi

    if ! getent passwd "${u}" &>/dev/null ; then
      continue
    fi

    ps -Fwww -u "${u}"
    killall -9 -u "${u}"
    deluser "${u}"
    rm -rf "/home/${u}"
  done
}

main "$@"
