#!/usr/bin/env bash

set -o errexit

main() {
  set -o xtrace
  shopt -s nullglob
  __install_packages
}

__install_packages() {
  sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
  sudo yum update -yqq
  sudo yum install -y \
    redhat-lsb-core \
    ca-certificates \
    curl \
    gawk \
    git \
    sudo \
    wget \
    rsync \
    python3 \
    python3-pip \
    ruby \
    gcc \
    gcc-c++ \
    gcc-gfortran \
    gettext \
    libtool \
    patch \
    openssl-devel \
    zlib-devel sqlite-devel bzip2-devel \
    redhat-rpm-config \
    rpm-build \
    procps \
    cmake \
    llvm \
    make \
    autoconf \
    automake \
    libtool \
    clang \
    ccache \
    python3.8 \
    python3.9 \
    libxml2-devel \
    libcurl-devel \
    libjpeg-devel \
    libpng-devel \
    libicu-devel \
    libmcrypt-devel \
    libtidy-devel \
    libxslt-devel \
    oniguruma \
    libzip-devel

    curl -L https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/bison-3.0.4-10.el8.x86_64.rpm -o /tmp/bison.rpm
    sudo dnf install -y /tmp/bison.rpm

    curl http://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/readline-devel-7.0-10.el8.x86_64.rpm -o /tmp/readline-devel.rpm
    sudo dnf install -y /tmp/readline-devel.rpm
    curl https://rpmfind.net/linux/centos/8-stream/PowerTools/x86_64/os/Packages/oniguruma-devel-6.8.2-2.el8.x86_64.rpm -o /tmp/oniguruma-devel.rpm
    sudo dnf install -y /tmp/oniguruma-devel.rpm


## Postgres
    sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    sudo dnf install --nogpgcheck -y postgresql12-server
    sudo systemctl enable postgresql-12
    sudo /usr/pgsql-12/bin/postgresql-12-setup initdb

## MySQL

  cd ~
  curl https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/numactl-libs-2.0.12-11.el8.x86_64.rpm -o /tmp/numactl-libs.rpm
  sudo dnf install -y  /tmp/numactl-libs.rpm
  sudo yum install -y cyrus-sasl-devel
  
  wget https://rpmfind.net/linux/centos/8-stream/PowerTools/x86_64/os/Packages/perl-common-sense-3.7.4-8.el8.x86_64.rpm
  sudo dnf install -y perl-common-sense-3.7.4-8.el8.x86_64.rpm
  wget https://rpmfind.net/linux/centos/8-stream/PowerTools/x86_64/os/Packages/perl-Types-Serialiser-1.0-12.el8.noarch.rpm
  sudo dnf install -y perl-Types-Serialiser-1.0-12.el8.noarch.rpm
  wget https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/perl-JSON-2.97.001-2.el8.noarch.rpm
  sudo dnf install -y perl-JSON-2.97.001-2.el8.noarch.rpm
  curl -L https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.28-1.el8.x86_64.rpm-bundle.tar -o /tmp/mysql-bundle.tar
  cd /tmp && tar -xf /tmp/mysql-bundle.tar && sudo dnf install -y mysql-community* && cd -
  sudo ln -s /usr/lib/systemd/system/mysqld.service /usr/lib/systemd/system/mysql.service
  sudo systemctl start mysqld
  sudo cat /var/log/mysqld.log
  MYSQLPASS=$(sudo grep "temporary password" /var/log/mysqld.log | cut -d'@' -f2 | cut -d':' -f2 | tr -d ' '| tr -d '\n')
  echo $MYSQLPASS
  sudo mysql -u root --password="$MYSQLPASS" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'DummyPAssword!1'"
  sudo mysql -u root --password="DummyPAssword!1" --connect-expired-password -e "UNINSTALL COMPONENT 'file://component_validate_password'"
  sudo mysql -u root --password="DummyPAssword!1" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY ''"
}

main "$@"
