#!/usr/bin/env bash
set -o errexit
set -o pipefail

main() {
  echo 'ensuring travis user'

  if [[ ! "${QUIET}" ]]; then
    set -o xtrace
  fi

  shopt -s nullglob
  __setup_travis_user
}

__setup_travis_user() {
  if ! getent passwd travis &>/dev/null; then
    if [[ -z "${TRAVIS_UID}" ]]; then
      useradd -p travis -s /bin/bash -m travis
    else
      useradd -p travis -s /bin/bash -m travis -u "${TRAVIS_UID}"
      groupmod -g "${TRAVIS_UID}" travis
      usermod -u "${TRAVIS_UID}" travis
    fi
  fi

  set +o xtrace
  : "${TRAVIS_USER_PASSWORD:=travis}"

  if [[ "${TRAVIS_OBFUSCATE_PASSWORD}" ]]; then
    TRAVIS_USER_PASSWORD="$(dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64)"
  fi

  echo "travis:${TRAVIS_USER_PASSWORD}" | chpasswd
  set -o xtrace

  __setup_sudoers
  __setup_travis_ssh

  mkdir -p /home/travis/bin

  mkdir -p /opt
  chmod 0755 /opt
  chown -R travis:travis /home/travis /opt
}

__setup_sudoers() {
  sed -i '/^%/d;/^# /d;/^$/d;/^#$/d;/^#includedir/d' /etc/sudoers
  echo '#includedir /etc/sudoers.d' >>/etc/sudoers

  mkdir -p /etc/sudoers.d

  if [[ -f /var/tmp/sudoers.d-travis ]]; then
    cp -v /var/tmp/sudoers.d-travis /etc/sudoers.d/travis
  else
    cat >/etc/sudoers.d/travis <<EOF
travis ALL=(ALL) NOPASSWD:ALL
Defaults !authenticate
Defaults !env_reset
Defaults !mail_badpass
EOF
  fi
  chmod 440 /etc/sudoers.d/travis
}

__setup_travis_ssh() {
  mkdir -p /home/travis/.ssh
  chmod 0700 /home/travis/.ssh

  touch /home/travis/.ssh/authorized_keys
  for f in /var/tmp/*_rsa.pub; do
    cat "${f}" >>/home/travis/.ssh/authorized_keys
  done
  chmod 0600 /home/travis/.ssh/authorized_keys
}

main "${@}"
