#!/usr/bin/env bash

set -ex

dpkg --list | awk '{ print $2 }' | grep linux-headers | xargs apt-get -y purge
dpkg --list | awk '{ print $2 }' | grep 'linux-image-3.*-generic' | grep -v `uname -r` | xargs apt-get -y purge
dpkg --list | awk '{ print $2 }' | grep linux-source | xargs apt-get -y purge
if [[ $CLEAN_DEV_PACKAGES ]] ; then
  dpkg --list | awk '{ print $2 }' | grep -- '-dev$' | xargs apt-get -y purge
fi
apt-get -y purge libx11-data xauth libxmuu1 libxcb1 libx11-6 libxext6
apt-get -y purge ppp pppconfig pppoeconf
apt-get -y purge popularity-contest
apt-get -y autoremove
apt-get -y clean
rm -rf VBoxGuestAdditions_*.iso VBoxGuestAdditions_*.iso.?
rm -f /tmp/chef*deb
