#!/usr/bin/env bash

# shellcheck disable=SC1091,SC1090
set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

main() {
  dist=$(lsb_release -cs)

  echo "Detected distribution: ${dist}"
  sudo apt update -yqq --fix-missing

  # Docker & Buildx setup
  echo "Setting up Docker + Buildx..."
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ${dist} stable" |
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt update -y
  sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin || echo "Docker install failed"

  echo "System update complete for ${dist}"
}

main "$@"
